services:
  - type: web
    name: chronohistory-backend
    runtime: python
    buildCommand: pip install -r Backend_TCC/requirements.txt
    startCommand: gunicorn --chdir Backend_TCC app:app
    envVars:
      - key: url
        sync: false
      - key: key
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ADM_USUARIO
        sync: false
      - key: ADM_SENHA
        sync: false
      - key: SECRET_KEY
        sync: false
