-- ============================================================
-- SCRIPT DE BANCO DE DADOS - PROJETO CHRONOHISTORY (Supabase / PostgreSQL)
-- ============================================================

-- Recria as tabelas para eliminar colunas antigas com tipos incompatíveis (ex: erro 22P02 quando ano era inteiro)
DROP TABLE IF EXISTS public.evento CASCADE;
DROP TABLE IF EXISTS public.usuario CASCADE;
DROP TABLE IF EXISTS public.imagens CASCADE;

-- 1. TABELA DE USUÁRIOS
CREATE TABLE public.usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user" VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    nome VARCHAR(150) NOT NULL,
    perfil VARCHAR(50) DEFAULT 'aluno',
    fase_jogo INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_usuario_user ON public.usuario("user");

-- 2. TABELA DE EVENTOS HISTÓRICOS (ano_inicio como TEXT para aceitar textos como 'c. 1.5 milhões a.C.')
CREATE TABLE public.evento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    periodo TEXT,
    ano_inicio TEXT,
    ano_termino TEXT,
    lugar TEXT,
    acontecimento TEXT,
    figuras_historicas JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_evento_periodo ON public.evento(periodo);

-- 3. TABELA DE IMAGENS / OBRAS DA GALERIA
CREATE TABLE public.imagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    pintor TEXT,
    periodo TEXT,
    ano TEXT,
    contexto TEXT,
    url TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- DADOS INICIAIS (SEED / MOCK DATA)
-- ============================================================

-- Inserir usuários iniciais para teste
INSERT INTO public.usuario ("user", senha, nome, perfil, fase_jogo)
VALUES 
    ('anaclara', '123', 'Ana Clara', 'aluno', 5),
    ('bruno', '123', 'Bruno Silva', 'aluno', 4),
    ('carla', '123', 'Carla Dias', 'aluno', 3),
    ('daniel', '123', 'Daniel Souza', 'aluno', 2),
    ('eduardo', '123', 'Eduardo Lima', 'aluno', 1)
ON CONFLICT DO NOTHING;

-- Inserir TODOS os 100 eventos do periodos.json na tabela public.evento
INSERT INTO public.evento (nome, periodo, ano_inicio, ano_termino, lugar, acontecimento, figuras_historicas)
VALUES
    ('Domínio do fogo', 'Pré-História', 'c. 1.5 milhões a.C. - 400 mil a.C.', '', 'África, Ásia e Europa', 'Diferentes espécies humanas aprenderam a controlar, produzir e manter o fogo para aquecimento, proteção e cocção de alimentos.', '["Homo erectus"]'::jsonb),
    ('Revolução Neolítica e surgimento da agricultura', 'Pré-História', 'c. 10.000 a.C. - 8.000 a.C.', '', 'Crescente Fértil (Oriente Médio)', 'Grupos humanos domesticaram plantas, como trigo e cevada, e animais, como ovelhas, cabras e bois, passando da caça-coleta para a produção de alimentos.', '["Povos natufianos"]'::jsonb),
    ('Primeiras ferramentas de pedra lascada', 'Pré-História', 'c. 2.6 milhões a.C.', '', 'África Oriental', 'Hominídeos antigos começaram a lascar pedras para criar ferramentas cortantes, iniciando o Paleolítico.', '["Homo habilis"]'::jsonb),
    ('Primeiras manifestações artísticas (pinturas rupestres)', 'Pré-História', 'c. 40.000 a.C. - 35.000 a.C.', '', 'Europa Ocidental e Indonésia', 'Humanos anatomicamente modernos produziram pinturas em cavernas, esculturas em marfim e osso e objetos rituais.', '["Homo sapiens"]'::jsonb),
    ('Migração para a América', 'Pré-História', 'c. 20.000 a.C. - 15.000 a.C.', '', 'Beringia e Américas', 'Grupos de caçadores-coletores migraram da Ásia para as Américas, possivelmente usando a região de Beringia durante a última era glacial.', '["Povos paleoíndios"]'::jsonb),
    ('Surgimento do Homo sapiens', 'Pré-História', 'c. 300.000 a.C.', '', 'África', 'Humanos anatomicamente modernos surgiram na África, com características físicas próximas às dos humanos atuais.', '["Homo sapiens"]'::jsonb),
    ('Expansão humana para fora da África', 'Pré-História', 'c. 70.000 a.C. - 50.000 a.C.', '', 'África, Oriente Médio, Ásia, Europa e Oceania', 'Grupos de Homo sapiens deixaram a África e se espalharam por diferentes continentes.', '["Homo sapiens"]'::jsonb),
    ('Primeiros rituais funerários', 'Pré-História', 'c. 100.000 a.C. - 40.000 a.C.', '', 'África, Oriente Médio e Europa', 'Humanos começaram a enterrar seus mortos com cuidado, às vezes acompanhados de objetos, pigmentos e sinais de ritual.', '["Homo sapiens", "Neandertais"]'::jsonb),
    ('Domesticação do cão', 'Pré-História', 'c. 15.000 a.C. - 12.000 a.C.', '', 'Eurásia', 'Lobos foram gradualmente domesticados por grupos humanos, dando origem aos primeiros cães.', '["Caçadores-coletores"]'::jsonb),
    ('Primeira metalurgia do cobre', 'Pré-História', 'c. 5000 a.C. - 3500 a.C.', '', 'Oriente Médio, Anatólia e Bálcãs', 'Comunidades humanas começaram a trabalhar metais, especialmente o cobre, produzindo ferramentas, armas e adornos.', '["Comunidades neolíticas"]'::jsonb),
    ('Primeiras aldeias sedentárias', 'Pré-História', 'c. 12.000 a.C. - 9.000 a.C.', '', 'Levante e Oriente Médio', 'Grupos humanos passaram a viver por mais tempo em aldeias, mesmo antes da agricultura plena.', '["Povos natufianos"]'::jsonb),
    ('Uso de instrumentos de osso e chifre', 'Pré-História', 'c. 50.000 a.C. - 20.000 a.C.', '', 'Europa, África e Ásia', 'Além da pedra, humanos passaram a usar ossos, chifres e madeira para produzir agulhas, arpões, pontas e ferramentas finas.', '["Homo sapiens"]'::jsonb),
    ('Povoamento da Austrália', 'Pré-História', 'c. 65.000 a.C. - 50.000 a.C.', '', 'Austrália e ilhas próximas', 'Grupos humanos chegaram à Austrália, provavelmente usando rotas marítimas curtas pelo Sudeste Asiático.', '["Primeiros povos aborígenes"]'::jsonb),
    ('Desenvolvimento de lâminas de pedra mais sofisticadas', 'Pré-História', 'c. 45.000 a.C. - 20.000 a.C.', '', 'Europa, África e Ásia', 'Humanos passaram a produzir lâminas menores, mais finas e especializadas para diferentes usos.', '["Homo sapiens"]'::jsonb),
    ('Construção de Göbekli Tepe', 'Pré-História', 'c. 9600 a.C. - 8000 a.C.', '', 'Anatólia (atual Turquia)', 'Grupos humanos construíram estruturas monumentais com pilares de pedra decorados com figuras de animais.', '["Comunidades pré-neolíticas da Anatólia"]'::jsonb),
    ('Domesticação de ovelhas e cabras', 'Pré-História', 'c. 9000 a.C. - 7000 a.C.', '', 'Crescente Fértil', 'Comunidades neolíticas passaram a criar ovelhas e cabras para obter carne, leite, couro e lã.', '["Pastores neolíticos"]'::jsonb),
    ('Invenção da cerâmica', 'Pré-História', 'c. 10.000 a.C. - 7000 a.C.', '', 'Ásia Oriental, Oriente Médio e outras regiões', 'Comunidades humanas passaram a fabricar recipientes de argila cozida para armazenar, cozinhar e transportar alimentos.', '["Comunidades neolíticas"]'::jsonb),
    ('Formação das primeiras redes de troca', 'Pré-História', 'c. 9000 a.C. - 5000 a.C.', '', 'Oriente Médio, Europa e Ásia', 'Comunidades começaram a trocar materiais como obsidiana, conchas, pedras especiais, alimentos e objetos artesanais.', '["Comunidades neolíticas"]'::jsonb),
    ('Desenvolvimento da tecelagem', 'Pré-História', 'c. 7000 a.C. - 5000 a.C.', '', 'Oriente Médio e Europa', 'Comunidades começaram a produzir tecidos a partir de fibras vegetais e animais.', '["Artesãos neolíticos"]'::jsonb),
    ('Crescimento das primeiras proto-cidades', 'Pré-História', 'c. 7000 a.C. - 4000 a.C.', '', 'Oriente Médio e Anatólia', 'Alguns assentamentos cresceram e passaram a concentrar grande população, produção artesanal e comércio.', '["Habitantes de Jericó e Çatalhöyük"]'::jsonb),
    ('Invenção da escrita', 'Idade Antiga', 'c. 3400 a.C. - 3200 a.C.', '', 'Mesopotâmia (atual Iraque)', 'Os sumérios desenvolveram a escrita cuneiforme, inicialmente para registrar transações comerciais e administrativas.', '["Sumérios"]'::jsonb),
    ('Unificação do Egito', 'Idade Antiga', 'c. 3100 a.C.', '', 'Vale do Nilo (Egito)', 'O faraó Menes, também associado a Narmer, unificou o Alto e o Baixo Egito, estabelecendo a primeira dinastia.', '["Menes (Narmer)"]'::jsonb),
    ('Código de Hamurabi', 'Idade Antiga', 'c. 1754 a.C.', '', 'Babilônia (Mesopotâmia)', 'O rei Hamurabi codificou leis em uma estela, tratando de comércio, propriedade, família, crimes e punições.', '["Hamurabi"]'::jsonb),
    ('Guerras Médicas', 'Idade Antiga', '499 a.C. - 449 a.C.', '', 'Grécia, Mar Egeu e Ásia Menor', 'Cidades-estado gregas, principalmente Atenas e Esparta, enfrentaram o Império Persa em uma série de conflitos.', '["Milcíades", "Leônidas", "Temístocles", "Xerxes I"]'::jsonb),
    ('Alexandre, o Grande', 'Idade Antiga', '336 a.C. - 323 a.C.', '', 'Macedônia, Grécia, Egito, Pérsia, Ásia Central e Índia', 'Alexandre III da Macedônia conquistou o Império Persa, chegou ao Egito e avançou até a região do rio Indo.', '["Alexandre, o Grande", "Aristóteles"]'::jsonb),
    ('Guerras Púnicas', 'Idade Antiga', '264 a.C. - 146 a.C.', '', 'Mediterrâneo Ocidental', 'Roma e Cartago travaram três guerras pelo controle do comércio e dos territórios mediterrâneos.', '["Aníbal Barca", "Cipião Africano", "Catão, o Velho"]'::jsonb),
    ('Democracia ateniense', 'Idade Antiga', '508 a.C. - 507 a.C.', '', 'Atenas (Grécia Antiga)', 'Clístenes instituiu reformas que organizaram a democracia direta em Atenas.', '["Clístenes", "Péricles"]'::jsonb),
    ('Fundação do Império Romano', 'Idade Antiga', '27 a.C.', '', 'Roma', 'Otávio Augusto tornou-se o primeiro imperador romano, encerrando a República.', '["Otávio Augusto", "Júlio César"]'::jsonb),
    ('Nascimento de Jesus Cristo', 'Idade Antiga', 'c. 4 a.C. - 6 d.C.', '', 'Belém (Judéia)', 'Jesus de Nazaré nasceu na Judéia e iniciou um movimento religioso baseado em ensinamentos como amor ao próximo, perdão e salvação.', '["Jesus Cristo", "Maria"]'::jsonb),
    ('Queda do Império Romano do Ocidente', 'Idade Antiga', '476 d.C.', '', 'Itália', 'O general germânico Odoacro depôs Rômulo Augusto, último imperador romano do Ocidente.', '["Rômulo Augusto", "Odoacro"]'::jsonb),
    ('Formação do Império Persa Aquemênida', 'Idade Antiga', 'c. 550 a.C.', '', 'Pérsia, Mesopotâmia, Egito e Ásia Menor', 'Ciro, o Grande, unificou os persas e iniciou a expansão do Império Aquemênida.', '["Ciro, o Grande", "Dario I"]'::jsonb),
    ('Fundação da República Romana', 'Idade Antiga', '509 a.C.', '', 'Roma', 'Segundo a tradição romana, o último rei, Tarquínio, o Soberbo, foi expulso, dando início à República Romana.', '["Lúcio Júnio Bruto"]'::jsonb),
    ('Guerra do Peloponeso', 'Idade Antiga', '431 a.C. - 404 a.C.', '', 'Grécia Antiga', 'Atenas e Esparta lideraram blocos rivais em uma longa guerra pelo controle do mundo grego.', '["Péricles", "Lisandro", "Tucídides"]'::jsonb),
    ('Édito de Milão', 'Idade Antiga', '313 d.C.', '', 'Império Romano', 'Constantino e Licínio concederam liberdade religiosa aos cristãos no Império Romano.', '["Constantino", "Licínio"]'::jsonb),
    ('Divisão definitiva do Império Romano', 'Idade Antiga', '395 d.C.', '', 'Império Romano do Ocidente e do Oriente', 'Após a morte de Teodósio I, o Império Romano foi dividido entre seus filhos Honório e Arcádio.', '["Teodósio I", "Honório", "Arcádio"]'::jsonb),
    ('Civilização do Vale do Indo', 'Idade Antiga', 'c. 2600 a.C. - 1900 a.C.', '', 'Vale do Rio Indo (atual Paquistão e noroeste da Índia)', 'Cidades como Harappa e Mohenjo-Daro desenvolveram planejamento urbano, sistemas de drenagem e comércio.', '["Povos harapenses"]'::jsonb),
    ('Dinastia Qin e unificação da China', 'Idade Antiga', '221 a.C.', '', 'China', 'Qin Shi Huang unificou diversos reinos chineses e tornou-se o primeiro imperador da China.', '["Qin Shi Huang"]'::jsonb),
    ('Primeiros Jogos Olímpicos antigos', 'Idade Antiga', '776 a.C.', '', 'Olímpia (Grécia)', 'Cidades gregas passaram a participar de competições atléticas em honra a Zeus.', '["Atletas gregos"]'::jsonb),
    ('Ashoka e a expansão do Budismo', 'Idade Antiga', 'c. 268 a.C. - 232 a.C.', '', 'Índia', 'O imperador Ashoka, da dinastia Máuria, adotou o Budismo após a Guerra de Kalinga e passou a promover princípios de não violência.', '["Ashoka"]'::jsonb),
    ('Édito de Tessalônica', 'Idade Antiga', '380 d.C.', '', 'Império Romano', 'O imperador Teodósio I declarou o cristianismo niceno como religião oficial do Império Romano.', '["Teodósio I"]'::jsonb),
    ('Reino Franco e Carlos Magno', 'Idade Média', '768 d.C. - 814 d.C.', '', 'França, Alemanha, Itália e Países Baixos', 'Carlos Magno conquistou vastos territórios na Europa Ocidental e foi coroado Imperador dos Romanos pelo Papa Leão III em 800.', '["Carlos Magno", "Papa Leão III"]'::jsonb),
    ('Hégira (fundação do Islã)', 'Idade Média', '622 d.C.', '', 'Meca e Medina', 'Maomé migrou de Meca para Medina, formando a primeira comunidade muçulmana organizada.', '["Maomé"]'::jsonb),
    ('Idade de Ouro Islâmica', 'Idade Média', '750 d.C. - 1258 d.C.', '', 'Bagdá, Córdoba, Cairo e outros centros islâmicos', 'O mundo islâmico viveu grande florescimento científico, filosófico, cultural e econômico.', '["Al-Khwarizmi", "Avicena (Ibn Sina)", "Averróis (Ibn Rushd)"]'::jsonb),
    ('Cisma do Oriente', 'Idade Média', '1054 d.C.', '', 'Constantinopla e Roma', 'Conflitos entre o Papa de Roma e o Patriarca de Constantinopla levaram à divisão entre Igreja Católica e Igreja Ortodoxa.', '["Papa Leão IX", "Patriarca Miguel Cerulário"]'::jsonb),
    ('Conquista normanda da Inglaterra', 'Idade Média', '1066 d.C.', '', 'Inglaterra', 'Guilherme, Duque da Normandia, derrotou Haroldo II na Batalha de Hastings e tornou-se rei da Inglaterra.', '["Guilherme, o Conquistador", "Haroldo II"]'::jsonb),
    ('As Cruzadas', 'Idade Média', '1095 d.C. - 1291 d.C.', '', 'Jerusalém e Oriente Médio', 'Expedições militares cristãs foram organizadas para conquistar ou manter territórios considerados sagrados.', '["Papa Urbano II", "Saladino", "Ricardo Coração de Leão"]'::jsonb),
    ('Carta Magna', 'Idade Média', '1215 d.C.', '', 'Inglaterra', 'O rei João Sem Terra foi pressionado por nobres a aceitar a Carta Magna, limitando poderes reais.', '["João Sem Terra"]'::jsonb),
    ('Guerra dos Cem Anos', 'Idade Média', '1337 d.C. - 1453 d.C.', '', 'França e Países Baixos', 'França e Inglaterra travaram uma longa guerra por disputas dinásticas e territoriais.', '["Joana d''Arc", "Henrique V"]'::jsonb),
    ('Peste Negra', 'Idade Média', '1347 d.C. - 1351 d.C.', '', 'Europa', 'Uma pandemia de peste bubônica devastou a Europa, matando uma parcela enorme da população.', '["Yersinia pestis"]'::jsonb),
    ('Queda de Constantinopla', 'Idade Média', '1453 d.C.', '', 'Constantinopla (atual Istambul)', 'O sultão otomano Mehmed II conquistou Constantinopla após um cerco de 53 dias.', '["Mehmed II", "Constantino XI Paleólogo"]'::jsonb),
    ('Feudalismo europeu', 'Idade Média', 'c. 800 d.C. - 1200 d.C.', '', 'Europa Ocidental', 'A sociedade europeia organizou-se em torno de relações de vassalagem, posse de terras e trabalho servil.', '["Senhores feudais", "Servos"]'::jsonb),
    ('Renascimento comercial e urbano', 'Idade Média', 'c. 1000 d.C. - 1300 d.C.', '', 'Europa Ocidental', 'O comércio cresceu, cidades se expandiram e novas rotas mercantis ligaram feiras, portos e centros urbanos.', '["Mercadores", "Artesãos urbanos"]'::jsonb),
    ('Fundação das primeiras universidades europeias', 'Idade Média', 'c. 1088 d.C. - 1200 d.C.', '', 'Bolonha, Paris, Oxford e outras cidades', 'Instituições de ensino superior surgiram para estudar direito, teologia, medicina e artes liberais.', '["Mestres universitários", "Estudantes medievais"]'::jsonb),
    ('Reconquista Ibérica', 'Idade Média', '711 d.C. - 1492 d.C.', '', 'Península Ibérica', 'Reinos cristãos avançaram gradualmente sobre territórios muçulmanos na Península Ibérica.', '["Reis cristãos ibéricos", "Governantes muçulmanos de Al-Andalus"]'::jsonb),
    ('Invasões vikings', 'Idade Média', 'c. 793 d.C. - 1066 d.C.', '', 'Europa do Norte, Ilhas Britânicas, França e Atlântico Norte', 'Povos nórdicos realizaram ataques, comércio, colonização e navegação por várias regiões europeias.', '["Vikings"]'::jsonb),
    ('Sacro Império Romano-Germânico', 'Idade Média', '962 d.C.', '', 'Europa Central', 'Otão I foi coroado imperador, dando origem ao Sacro Império Romano-Germânico.', '["Otão I"]'::jsonb),
    ('Querela das Investiduras', 'Idade Média', '1075 d.C. - 1122 d.C.', '', 'Europa Ocidental', 'Papado e imperadores disputaram o direito de nomear bispos e controlar cargos eclesiásticos.', '["Papa Gregório VII", "Henrique IV"]'::jsonb),
    ('Império Mongol', 'Idade Média', '1206 d.C. - 1368 d.C.', '', 'Ásia e Europa Oriental', 'Gêngis Khan unificou tribos mongóis e iniciou a formação do maior império terrestre contínuo da história.', '["Gêngis Khan", "Kublai Khan"]'::jsonb),
    ('Marco Polo e as viagens ao Oriente', 'Idade Média', '1271 d.C. - 1295 d.C.', '', 'Europa, Ásia Central e China', 'Marco Polo viajou pela Ásia e relatou experiências no Império Mongol e na China.', '["Marco Polo", "Kublai Khan"]'::jsonb),
    ('Crise do século XIV', 'Idade Média', 'c. 1300 d.C. - 1400 d.C.', '', 'Europa', 'Fomes, guerras, peste, revoltas camponesas e instabilidade econômica atingiram a Europa.', '["Camponeses europeus", "Nobreza feudal"]'::jsonb),
    ('Imprensa de Gutenberg', 'Idade Moderna', 'c. 1440 d.C. - 1455 d.C.', '', 'Mainz, Alemanha', 'Johannes Gutenberg desenvolveu a prensa de tipos móveis e imprimiu a Bíblia de Gutenberg.', '["Johannes Gutenberg"]'::jsonb),
    ('Descobrimento do Brasil', 'Idade Moderna', '1500 d.C.', '', 'Brasil (Porto Seguro, atual Bahia)', 'A frota portuguesa liderada por Pedro Álvares Cabral chegou às terras que seriam chamadas de Brasil.', '["Pedro Álvares Cabral", "Pero Vaz de Caminha"]'::jsonb),
    ('Chegada de Colombo à América', 'Idade Moderna', '1492 d.C.', '', 'Caribe', 'Cristóvão Colombo, financiado pela Espanha, chegou à América ao tentar alcançar as Índias pelo oeste.', '["Cristóvão Colombo", "Reis Católicos"]'::jsonb),
    ('Reforma Protestante', 'Idade Moderna', '1517 d.C.', '', 'Alemanha', 'Martinho Lutero publicou suas 95 Teses criticando práticas da Igreja, como a venda de indulgências.', '["Martinho Lutero", "João Calvino", "Henrique VIII"]'::jsonb),
    ('Contrarreforma e Concílio de Trento', 'Idade Moderna', '1545 d.C. - 1563 d.C.', '', 'Trento, Itália', 'A Igreja Católica realizou o Concílio de Trento para responder à Reforma Protestante e reorganizar sua doutrina e disciplina.', '["Papa Paulo III", "Inácio de Loyola"]'::jsonb),
    ('Revolução Científica', 'Idade Moderna', '1543 d.C. - 1687 d.C.', '', 'Europa', 'Pensadores como Copérnico, Galileu, Kepler e Newton transformaram a compreensão do universo e da natureza.', '["Nicolau Copérnico", "Galileu Galilei", "Isaac Newton", "Johannes Kepler"]'::jsonb),
    ('Revolução Gloriosa e Declaração de Direitos', 'Idade Moderna', '1688 d.C. - 1689 d.C.', '', 'Inglaterra', 'O Parlamento depôs Jaime II e convidou Guilherme de Orange e Maria para governar sob limites legais.', '["Guilherme de Orange", "John Locke"]'::jsonb),
    ('Iluminismo', 'Idade Moderna', 'c. 1715 d.C. - 1789 d.C.', '', 'França, Escócia, Alemanha e Américas', 'Movimento intelectual valorizou razão, ciência, liberdade, tolerância e crítica ao absolutismo.', '["Voltaire", "Jean-Jacques Rousseau", "Montesquieu", "Denis Diderot", "Immanuel Kant"]'::jsonb),
    ('Independência dos Estados Unidos', 'Idade Moderna', '1776 d.C.', '', 'Filadélfia', 'As Treze Colônias declararam independência do Reino Unido por meio da Declaração de Independência.', '["George Washington", "Thomas Jefferson", "Benjamin Franklin"]'::jsonb),
    ('Revolução Industrial na Inglaterra (1ª fase)', 'Idade Moderna', '1760 d.C. - 1840 d.C.', '', 'Inglaterra', 'Máquinas a vapor, teares mecânicos e novas formas de produção transformaram a indústria têxtil e metalúrgica.', '["James Watt", "Richard Arkwright", "Adam Smith"]'::jsonb),
    ('Renascimento Cultural', 'Idade Moderna', 'c. 1300 d.C. - 1600 d.C.', '', 'Itália e Europa Ocidental', 'Artistas e intelectuais retomaram valores da Antiguidade clássica, valorizando o humanismo, a razão e a observação da natureza.', '["Leonardo da Vinci", "Michelangelo", "Petrarca"]'::jsonb),
    ('Tratado de Tordesilhas', 'Idade Moderna', '1494 d.C.', '', 'Tordesilhas, Espanha', 'Portugal e Espanha dividiram entre si áreas de exploração no Atlântico por meio de uma linha imaginária.', '["Reis Católicos", "Dom João II"]'::jsonb),
    ('Grandes Navegações', 'Idade Moderna', 'c. 1415 d.C. - 1600 d.C.', '', 'Atlântico, África, Ásia e Américas', 'Europeus, especialmente portugueses e espanhóis, exploraram rotas marítimas em busca de comércio, terras e riquezas.', '["Vasco da Gama", "Cristóvão Colombo", "Fernão de Magalhães"]'::jsonb),
    ('Conquista do Império Asteca', 'Idade Moderna', '1519 d.C. - 1521 d.C.', '', 'México', 'Hernán Cortés, com aliados indígenas, conquistou Tenochtitlán e derrubou o Império Asteca.', '["Hernán Cortés", "Montezuma II", "Malintzin"]'::jsonb),
    ('Conquista do Império Inca', 'Idade Moderna', '1532 d.C. - 1572 d.C.', '', 'Andes', 'Francisco Pizarro capturou Atahualpa e iniciou a conquista espanhola do Império Inca.', '["Francisco Pizarro", "Atahualpa"]'::jsonb),
    ('União Ibérica', 'Idade Moderna', '1580 d.C. - 1640 d.C.', '', 'Portugal, Espanha e colônias ultramarinas', 'Portugal e Espanha passaram a ser governados pelo mesmo rei após uma crise sucessória portuguesa.', '["Filipe II da Espanha"]'::jsonb),
    ('Invasões Holandesas no Brasil', 'Idade Moderna', '1624 d.C. - 1654 d.C.', '', 'Bahia e Pernambuco', 'Holandeses tentaram controlar áreas produtoras de açúcar no Brasil, especialmente no Nordeste.', '["Maurício de Nassau", "Companhia das Índias Ocidentais"]'::jsonb),
    ('Guerra dos Trinta Anos', 'Idade Moderna', '1618 d.C. - 1648 d.C.', '', 'Europa Central', 'Conflito religioso e político envolveu estados católicos e protestantes, especialmente no Sacro Império.', '["Fernando II", "Gustavo Adolfo", "Cardeal Richelieu"]'::jsonb),
    ('Absolutismo francês de Luís XIV', 'Idade Moderna', '1643 d.C. - 1715 d.C.', '', 'França', 'Luís XIV centralizou o poder real, fortaleceu o Estado francês e transformou Versalhes em símbolo do absolutismo.', '["Luís XIV", "Jean-Baptiste Colbert"]'::jsonb),
    ('Inconfidência Mineira', 'Idade Moderna', '1789 d.C.', '', 'Vila Rica, Minas Gerais', 'Elite colonial mineira organizou uma conspiração contra a cobrança de impostos portugueses e o domínio metropolitano.', '["Tiradentes", "Tomás Antônio Gonzaga", "Cláudio Manuel da Costa"]'::jsonb),
    ('Revolução Francesa', 'Idade Contemporânea', '1789 d.C. - 1799 d.C.', '', 'França', 'A população francesa, influenciada pelo Iluminismo e pela crise social, revoltou-se contra o absolutismo e os privilégios do Antigo Regime.', '["Maximilien Robespierre", "Napoleão Bonaparte", "Marquês de Lafayette"]'::jsonb),
    ('Era Napoleônica', 'Idade Contemporânea', '1799 d.C. - 1815 d.C.', '', 'Europa', 'Napoleão Bonaparte assumiu o poder na França, tornou-se imperador e conquistou grande parte da Europa.', '["Napoleão Bonaparte", "Duque de Wellington", "Czar Alexandre I"]'::jsonb),
    ('Independências na América Latina', 'Idade Contemporânea', '1808 d.C. - 1826 d.C.', '', 'América Espanhola e Portuguesa', 'A crise dos impérios ibéricos abriu espaço para movimentos de independência liderados por elites locais e líderes militares.', '["Simón Bolívar", "José de San Martín", "Dom Pedro I", "Miguel Hidalgo"]'::jsonb),
    ('Primavera dos Povos (Revoluções de 1848)', 'Idade Contemporânea', '1848 d.C.', '', 'Europa', 'Revoluções liberais, nacionalistas e sociais ocorreram em várias regiões europeias.', '["Luís Napoleão Bonaparte", "Karl Marx", "Lajos Kossuth"]'::jsonb),
    ('Unificação da Alemanha', 'Idade Contemporânea', '1864 d.C. - 1871 d.C.', '', 'Alemanha', 'A Prússia, liderada por Bismarck, conduziu guerras e negociações que unificaram os estados alemães.', '["Otto von Bismarck", "Guilherme I"]'::jsonb),
    ('Revolução Industrial (2ª fase)', 'Idade Contemporânea', '1870 d.C. - 1914 d.C.', '', 'Europa, EUA e Japão', 'Eletricidade, aço, petróleo, motor de combustão, telefone, rádio e linha de montagem transformaram a produção.', '["Thomas Edison", "Nikola Tesla", "Henry Ford", "Karl Benz"]'::jsonb),
    ('Imperialismo e Partilha da África', 'Idade Contemporânea', '1881 d.C. - 1914 d.C.', '', 'África, Ásia e Oceania', 'Potências europeias dividiram territórios africanos e asiáticos em busca de matérias-primas, mercados e prestígio.', '["Leopoldo II", "Cecil Rhodes", "Otto von Bismarck"]'::jsonb),
    ('Primeira Guerra Mundial', 'Idade Contemporânea', '1914 d.C. - 1918 d.C.', '', 'Principalmente Europa', 'O assassinato de Francisco Ferdinando desencadeou alianças militares e uma guerra marcada por trincheiras, metralhadoras, tanques, aviões e gás tóxico.', '["Francisco Ferdinando", "Woodrow Wilson", "Kaiser Guilherme II"]'::jsonb),
    ('Revolução Russa e criação da URSS', 'Idade Contemporânea', '1917 d.C.', '', 'Rússia', 'A Revolução de Fevereiro derrubou o czar e a Revolução de Outubro levou os bolcheviques ao poder.', '["Vladimir Lenin", "Leon Trotsky", "Josef Stalin", "Nicolau II"]'::jsonb),
    ('Grande Depressão', 'Idade Contemporânea', '1929 d.C. - 1939 d.C.', '', 'Mundial, iniciada nos EUA', 'A quebra da Bolsa de Nova York desencadeou crise econômica mundial, desemprego em massa e falências.', '["Franklin D. Roosevelt", "Herbert Hoover", "John Maynard Keynes"]'::jsonb),
    ('Ascensão do Nazismo e Fascismo', 'Idade Contemporânea', '1922 d.C. - 1933 d.C.', '', 'Itália e Alemanha', 'Mussolini chegou ao poder na Itália e Hitler tornou-se chanceler da Alemanha, consolidando regimes totalitários.', '["Adolf Hitler", "Benito Mussolini", "Francisco Franco"]'::jsonb),
    ('Segunda Guerra Mundial', 'Idade Contemporânea', '1939 d.C. - 1945 d.C.', '', 'Europa, Ásia, África, Atlântico e Pacífico', 'A invasão da Polônia pela Alemanha nazista desencadeou uma guerra global entre Aliados e Eixo.', '["Adolf Hitler", "Winston Churchill", "Franklin D. Roosevelt", "Josef Stalin", "Harry S. Truman"]'::jsonb),
    ('Guerra Fria', 'Idade Contemporânea', '1947 d.C. - 1991 d.C.', '', 'Mundial', 'EUA e URSS disputaram influência global por meio de ideologia, armas, espionagem, tecnologia e guerras indiretas.', '["Harry S. Truman", "Josef Stalin", "John F. Kennedy", "Ronald Reagan", "Mikhail Gorbachev"]'::jsonb),
    ('Descolonização da África e Ásia', 'Idade Contemporânea', '1945 d.C. - 1975 d.C.', '', 'África e Ásia', 'Colônias europeias conquistaram independência após a Segunda Guerra Mundial, muitas vezes por negociações ou guerras.', '["Mahatma Gandhi", "Kwame Nkrumah", "Ho Chi Minh"]'::jsonb),
    ('Revolução Digital e Internet', 'Idade Contemporânea', '1970 d.C. - presente', '', 'Mundial', 'Microprocessadores, computadores pessoais, internet, web, smartphones e inteligência artificial transformaram a vida cotidiana.', '["Tim Berners-Lee", "Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Elon Musk"]'::jsonb),
    ('Independência do Brasil', 'Idade Contemporânea', '1822 d.C.', '', 'Brasil', 'Dom Pedro proclamou a independência do Brasil em relação a Portugal, tornando-se depois imperador.', '["Dom Pedro I", "José Bonifácio"]'::jsonb),
    ('Abolição da escravidão no Brasil', 'Idade Contemporânea', '1888 d.C.', '', 'Brasil', 'A Lei Áurea aboliu oficialmente a escravidão no Brasil.', '["Princesa Isabel", "Luís Gama", "André Rebouças"]'::jsonb),
    ('Chegada do homem à Lua', 'Idade Contemporânea', '1969 d.C.', '', 'Lua', 'A missão Apollo 11 levou Neil Armstrong e Buzz Aldrin à superfície lunar.', '["Neil Armstrong", "Buzz Aldrin", "Michael Collins"]'::jsonb),
    ('Queda do Muro de Berlim', 'Idade Contemporânea', '1989 d.C.', '', 'Berlim, Alemanha', 'Manifestantes derrubaram barreiras do Muro de Berlim após abertura das fronteiras pela Alemanha Oriental.', '["Mikhail Gorbachev", "Helmut Kohl"]'::jsonb),
    ('Dissolução da União Soviética', 'Idade Contemporânea', '1991 d.C.', '', 'URSS', 'A União Soviética foi dissolvida após crise econômica, reformas políticas, nacionalismos internos e perda de controle do Partido Comunista.', '["Mikhail Gorbachev", "Boris Yeltsin"]'::jsonb);

-- ============================================================
-- POLÍTICAS DE SEGURANÇA (Row Level Security - RLS)
-- ============================================================
ALTER TABLE public.usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.imagens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir tudo na tabela usuario" ON public.usuario;
CREATE POLICY "Permitir tudo na tabela usuario" ON public.usuario FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir tudo na tabela evento" ON public.evento;
CREATE POLICY "Permitir tudo na tabela evento" ON public.evento FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir tudo na tabela imagens" ON public.imagens;
CREATE POLICY "Permitir tudo na tabela imagens" ON public.imagens FOR ALL USING (true) WITH CHECK (true);